
name: Build

on: 
  push:
    tags:
      - "Release v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: false

jobs:
  release:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist
        shell: bash

      - name: Upload a Release Asset (linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: TMC_Launcher_Linux
          path: |
            dist/*.AppImage
            dist/*.yml

      - name: Upload a Release Asset (mac)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: TMC_Launcher_Mac
          path: |
            dist/*.dmg
            dist/*.blockmap
            dist/*.AppImage
            dist/*.yml
            dist/.icon-ico
            dist/.icon-icns

      - name: Upload a Release Asset (win)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: TMC_Launcher_Win
          path: dist
      
      - name: Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: testtag3
          draft: true
          files: foo.txt